### ISSUE TITLE
Received 500 error when Auth with brime

### ISSUE THREAD

**Issue by DigitalEnki** [artandor/multistream-tools#13]
As title states, I authenticated successfully with Brime but the callback threw a 500 error.

Authenticated with twitch ok though 🙂

**Comment by vasilvestre** [comment]
Those errors come from Brime.. we should definitly add a message saying that Brime API isn't working at the moment.

**Comment by artandor** [comment]
According to geeken, this error was on brime's side because we had multiple ways to auth with our account, leading to their system sending an issue sometimes. This was supposedly solved by removing unused auth solutions from our account.
