### ISSUE TITLE
Youtube title not updating

### ISSUE THREAD

**Issue by artandor** [artandor/multistream-tools#53]
**Describe the bug**
Title on youtube is not updating.

**To Reproduce**
1. Login with an account that has youtube creator enabled
2. Go live
2. Go to https://multistream-tools.live/update-stream-infos
2. Update the title

**Expected behavior**
The title should update like any other platform.

**Additional context**

![image](https://user-images.githubusercontent.com/22364556/152540575-b2d53174-6411-44f5-b77b-26ef4df8ef77.png)

**Comment by mistertest** [comment]
Hello.
Realy great and usefull app for multi streaming. 
I will use it with my custom RMTP server on my vps server for muti streaming. 
I can confirm, that there is error for updating titles and cateory information for youtube. No problems for twitch.

**Comment by artandor** [comment]
After removing multistream tools from my google apps https://myaccount.google.com/u/2/permissions and logging again with youtube https://multistream-tools.live/connect/google i was not able to reproduce the bug. @mistertest can you try to do it aswell and tell me how it worked for you ?

I'll continue to monitor the issue, to understand wether it was a temporary issue or if it's still here and i can't see it.

**Comment by artandor** [comment]
After some monitoring, i can confirm that the Youtube provider works, but that the tokens issued by google seem very short. One should investigate on having a longer life for the refresh token, but i have no time for that atm.

**Comment by mistertest** [comment]
> After removing multistream tools from my google apps https://myaccount.google.com/u/2/permissions and logging again with youtube https://multistream-tools.live/connect/google i was not able to reproduce the bug. @mistertest can you try to do it aswell and tell me how it worked for you ? Please remember that, to update your title on youtube, you must be streaming there already.
> 
> I'll continue to monitor the issue, to understand wether it was a temporary issue or if it's still here and i can't see it.

Thank you very much I will testing the app  soon this week. Great tool, great dev, thx.
